# -*- coding: utf-8 -*-
"""championship-cube-era-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSwaBZwXUwJupPXmIV_m2fpSayopnHcd
"""

# Championship Cube — Complete Analysis Script
# Supporting research for MIT Sloan Sports Analytics Conference 2027
# Data sourced from Basketball Reference

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# ── 1. LOAD DATA ──────────────────────────────────────────────
champions = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-champions.csv')

losers = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-losers.csv')

# Clean column names
champions.columns = champions.columns.str.strip()
losers.columns = losers.columns.str.strip()

print("Data loaded successfully")
print(f"Champions: {len(champions)} rows")
print(f"Losers: {len(losers)} rows")

# ── 2. ERA ANALYSIS ───────────────────────────────────────────
era_champs = champions.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()
era_losers = losers.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()

print("\nCHAMPIONS BY ERA:")
print(era_champs)
print("\nFINALS LOSERS BY ERA:")
print(era_losers)

# ── 3. GAP ANALYSIS ───────────────────────────────────────────
print("\nSRS GAP BY ERA (Champions minus Losers):")
print(era_champs['SRS'] - era_losers['SRS'])

print("\nNet Rating GAP BY ERA:")
print(era_champs['Net Rating'] - era_losers['Net Rating'])

print("\nDRtg GAP BY ERA:")
print(era_champs['DRtg'] - era_losers['DRtg'])

# ── 4. LOGISTIC REGRESSION ────────────────────────────────────
champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
combined = pd.concat([champions, losers])
combined.columns = combined.columns.str.strip()

X = combined[['SRS', 'Net Rating', 'DRtg']].values
y = combined['Result_Binary'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression()
model.fit(X_scaled, y)

print("\nLOGISTIC REGRESSION RESULTS:")
print(f"SRS Coefficient: {model.coef_[0][0]:.3f}")
print(f"Net Rating Coefficient: {model.coef_[0][1]:.3f}")
print(f"DRtg Coefficient: {model.coef_[0][2]:.3f}")
print(f"Classification Accuracy: {model.score(X_scaled, y):.1%}")

print(champions[champions.duplicated(subset=['Year'], keep=False)])
print(losers[losers.duplicated(subset=['Year'], keep=False)])

champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
print(f"Champions: {len(champions)} rows before any modifications")

print(champions['Year'].value_counts().sort_index())

# Extended Analysis — Sections 2.4 and 2.5

# 3PA and 3P% by era
era_3p = champions.groupby('Era')[['3PA', '3P%']].mean()
print("Champion 3PA and 3P% by Era:")
print(era_3p)

# Pace evolution
print("\nPace Evolution by Era:")
print(f"Physical Era Champions: {champions[champions['Era']=='P']['Pace'].mean():.2f}")
print(f"Transition Era Champions: {champions[champions['Era']=='T']['Pace'].mean():.2f}")
print(f"Analytics Era Champions: {champions[champions['Era']=='A']['Pace'].mean():.2f}")

# Overall champion vs loser across all eras
print("\nOVERALL CHAMPIONS vs LOSERS (all eras combined):")
print(f"Champion avg SRS: {champions['SRS'].mean():.2f}")
print(f"Loser avg SRS: {losers['SRS'].mean():.2f}")
print(f"Champion avg DRtg: {champions['DRtg'].mean():.2f}")
print(f"Loser avg DRtg: {losers['DRtg'].mean():.2f}")
print(f"Champion avg Net Rating: {champions['Net Rating'].mean():.2f}")
print(f"Loser avg Net Rating: {losers['Net Rating'].mean():.2f}")

# SRS threshold analysis
high_srs_champs = len(champions[champions['SRS'] >= 5])
high_srs_losers = len(losers[losers['SRS'] >= 5])
print(f"\nChampions with SRS above 5: {high_srs_champs} out of {len(champions)}")
print(f"Losers with SRS above 5: {high_srs_losers} out of {len(losers)}")

# Lowest and highest SRS champions
print(f"\nLowest SRS champion: {champions.loc[champions['SRS'].idxmin(), 'Year']} {champions.loc[champions['SRS'].idxmin(), 'Team']} — SRS: {champions['SRS'].min():.2f}")
print(f"Highest SRS champion: {champions.loc[champions['SRS'].idxmax(), 'Year']} {champions.loc[champions['SRS'].idxmax(), 'Team']} — SRS: {champions['SRS'].max():.2f}")

# Analytics Era 3PA comparison
analytics_champs = champions[champions['Era'] == 'A']
analytics_losers = losers[losers['Era'] == 'A']
print(f"\nAnalytics Era 3PA:")
print(f"Champion avg 3PA: {analytics_champs['3PA'].mean():.1f}")
print(f"Loser avg 3PA: {analytics_losers['3PA'].mean():.1f}")

# Net Rating threshold
high_nr_champs = len(champions[champions['Net Rating'] >= 5])
high_nr_losers = len(losers[losers['Net Rating'] >= 5])
print(f"\nChampions with Net Rating above 5: {high_nr_champs} out of {len(champions)}")
print(f"Losers with Net Rating above 5: {high_nr_losers} out of {len(losers)}")

# DRtg threshold
low_drtg_champs = len(champions[champions['DRtg'] <= 107])
low_drtg_losers = len(losers[losers['DRtg'] <= 107])
print(f"\nChampions with DRtg at or below 107: {low_drtg_champs} out of {len(champions)}")
print(f"Losers with DRtg at or below 107: {low_drtg_losers} out of {len(losers)}")

# ── COACH FACE ANALYSIS ──────────────────────────────────────
import pandas as pd

coach_data = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-coach-face.csv', encoding='latin1')

coach_data.columns = coach_data.columns.str.strip()

print("COACH FACE SCORES BY RESULT:")
print(coach_data.groupby('Result')['Coach Face Score'].mean())

print("\nCHAMPION COACH FACE SCORES:")
print(coach_data[coach_data['Result']=='Champion'][['Year','Team','Coach','Coach Face Score']])

print("\nLOSER COACH FACE SCORES:")
print(coach_data[coach_data['Result']=='Loser'][['Year','Team','Coach','Coach Face Score']])

print(f"\nAverage Champion Coach Face Score: {coach_data[coach_data['Result']=='Champion']['Coach Face Score'].mean():.2f}")
print(f"Average Loser Coach Face Score: {coach_data[coach_data['Result']=='Loser']['Coach Face Score'].mean():.2f}")
print(f"Gap: {coach_data[coach_data['Result']=='Champion']['Coach Face Score'].mean() - coach_data[coach_data['Result']=='Loser']['Coach Face Score'].mean():.2f}")



# -*- coding: utf-8 -*-
"""championship-cube-era-analysis (corrected)

Supporting research for MIT Sloan Sports Analytics Conference 2027
Data sourced from Basketball Reference, loaded live from the repo.
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score

# ── 1. LOAD DATA ──────────────────────────────────────────────
champions = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-champions.csv')
losers = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-losers.csv')

champions.columns = champions.columns.str.strip()
losers.columns = losers.columns.str.strip()

print("Data loaded successfully")
print(f"Champions: {len(champions)} rows")
print(f"Losers: {len(losers)} rows")

# Data-quality check - kept from the original, this is a genuinely good habit
dup_c = champions[champions.duplicated(subset=['Year'], keep=False)]
dup_l = losers[losers.duplicated(subset=['Year'], keep=False)]
print(f"Duplicate years - champions: {len(dup_c)}, losers: {len(dup_l)}")

# ── 2. ERA ANALYSIS ───────────────────────────────────────────
era_champs = champions.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()
era_losers = losers.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()

print("\nCHAMPIONS BY ERA:")
print(era_champs)
print("\nFINALS LOSERS BY ERA:")
print(era_losers)

# ── 3. GAP ANALYSIS ───────────────────────────────────────────
print("\nSRS GAP BY ERA (Champions minus Losers):")
print(era_champs['SRS'] - era_losers['SRS'])

print("\nNet Rating GAP BY ERA:")
print(era_champs['Net Rating'] - era_losers['Net Rating'])

print("\nDRtg GAP BY ERA:")
print(era_champs['DRtg'] - era_losers['DRtg'])

# ── 4. LOGISTIC REGRESSION ────────────────────────────────────
champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
combined = pd.concat([champions, losers])
combined.columns = combined.columns.str.strip()

print("\n" + "=" * 70)
print("MODEL A: SRS + Net Rating + DRtg together")
print("=" * 70)
print("NOTE: SRS and Net Rating are 0.98 correlated in this dataset.")
print("Combining them destabilizes the coefficients - shown below for")
print("transparency, but Model B (SRS alone) is the defensible one.")

X_multi = combined[['SRS', 'Net Rating', 'DRtg']].values
y = combined['Result_Binary'].values

scaler = StandardScaler()
X_multi_scaled = scaler.fit_transform(X_multi)

# Coefficients + actual significance (statsmodels gives p-values; sklearn doesn't)
Xc = sm.add_constant(X_multi_scaled)
sm_model = sm.Logit(y, Xc).fit(disp=0)
coef_names = ['const', 'SRS', 'Net Rating', 'DRtg']
print("\nCoefficients and significance:")
for name, coef, p in zip(coef_names, sm_model.params, sm_model.pvalues):
    sig = "significant (p<0.05)" if p < 0.05 else "NOT significant"
    print(f"  {name:12s} coef={coef:+.3f}   p={p:.3f}   {sig}")

# Honest accuracy: cross-validated, not in-sample
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_acc_multi = cross_val_score(LogisticRegression(), X_multi_scaled, y, cv=skf, scoring='accuracy')
print(f"\n5-fold CV accuracy: {cv_acc_multi.mean()*100:.1f}%  (NOT in-sample .score() - that number is always optimistic)")

print("\n" + "=" * 70)
print("MODEL B: SRS alone - the defensible, headline model")
print("=" * 70)

X_single = combined[['SRS']].values
sm_single = sm.Logit(y, sm.add_constant(X_single)).fit(disp=0)
print("\nCoefficient and significance:")
for name, coef, p in zip(['const', 'SRS'], sm_single.params, sm_single.pvalues):
    sig = "significant (p<0.05)" if p < 0.05 else "NOT significant"
    print(f"  {name:12s} coef={coef:+.3f}   p={p:.4f}   {sig}")

cv_acc_single = cross_val_score(LogisticRegression(class_weight='balanced', random_state=42),
                                 X_single, y, cv=skf, scoring='accuracy')
cv_auc_single = cross_val_score(LogisticRegression(class_weight='balanced', random_state=42),
                                 X_single, y, cv=skf, scoring='roc_auc')
print(f"\n5-fold CV accuracy: {cv_acc_single.mean()*100:.1f}%")
print(f"5-fold CV AUC:      {cv_auc_single.mean():.3f}")

# Matched-pair framing - the most intuitive real result for the abstract
champs_sorted = champions.sort_values('Year').reset_index(drop=True)
losers_sorted = losers.sort_values('Year').reset_index(drop=True)
better_srs_won = (champs_sorted['SRS'].values > losers_sorted['SRS'].values).sum()
print(f"\nMatched-pair result: the team with the better SRS won the actual")
print(f"Finals matchup in {better_srs_won}/{len(champs_sorted)} series "
      f"({better_srs_won/len(champs_sorted)*100:.1f}%), 1990-2026.")

# ── OUT-OF-SAMPLE TEST (no new data needed - just a different split) ──
print("\n" + "=" * 70)
print("OUT-OF-SAMPLE TEST: train on 1990-2018, test on 2019-2026")
print("=" * 70)

train = combined[combined['Year'] <= 2018]
test = combined[combined['Year'] >= 2019]
print(f"Train: {len(train)} teams (1990-2018)")
print(f"Test:  {len(test)} teams (2019-2026), {test['Year'].nunique()} seasons - never seen in training")

oos_model = LogisticRegression(class_weight='balanced', random_state=42)
oos_model.fit(train[['SRS']], train['Result_Binary'])
oos_acc = oos_model.score(test[['SRS']], test['Result_Binary'])
print(f"\nOut-of-sample accuracy: {oos_acc*100:.1f}%")

test_sorted = test.sort_values('Year')
hits = 0
total = 0
for yr in test_sorted['Year'].unique():
    yr_data = test_sorted[test_sorted['Year'] == yr]
    champ_row = yr_data[yr_data['Result_Binary'] == 1]
    loser_row = yr_data[yr_data['Result_Binary'] == 0]
    if len(champ_row) and len(loser_row):
        champ_prob = oos_model.predict_proba(champ_row[['SRS']])[0][1]
        loser_prob = oos_model.predict_proba(loser_row[['SRS']])[0][1]
        correct = champ_prob > loser_prob
        total += 1
        hits += int(correct)
        print(f"  {yr} {champ_row['Team'].values[0]}: "
              f"{'correctly identified as more likely champion' if correct else 'model favored the other team'}")

print(f"\nMatched-pair out-of-sample result: {hits}/{total} champions correctly "
      f"identified ({hits/total*100:.1f}%) using only pre-2019 data.")
print("NOTE: n=8 seasons in the test window - small sample, directional evidence")
print("only. Consistent with the in-sample finding: SRS alone caps well short of")
print("certainty, supporting the case that the other five Cube dimensions matter.")

# ── EXTENDED ANALYSIS — Sections 2.4 and 2.5 ──────────────────
era_3p = champions.groupby('Era')[['3PA', '3P%']].mean()
print("\nChampion 3PA and 3P% by Era:")
print(era_3p)

print("\nPace Evolution by Era:")
print(f"Physical Era Champions: {champions[champions['Era']=='P']['Pace'].mean():.2f}")
print(f"Transition Era Champions: {champions[champions['Era']=='T']['Pace'].mean():.2f}")
print(f"Analytics Era Champions: {champions[champions['Era']=='A']['Pace'].mean():.2f}")

print("\nOVERALL CHAMPIONS vs LOSERS (all eras combined):")
print(f"Champion avg SRS: {champions['SRS'].mean():.2f}")
print(f"Loser avg SRS: {losers['SRS'].mean():.2f}")
print(f"Champion avg DRtg: {champions['DRtg'].mean():.2f}")
print(f"Loser avg DRtg: {losers['DRtg'].mean():.2f}")
print(f"Champion avg Net Rating: {champions['Net Rating'].mean():.2f}")
print(f"Loser avg Net Rating: {losers['Net Rating'].mean():.2f}")

high_srs_champs = len(champions[champions['SRS'] >= 5])
high_srs_losers = len(losers[losers['SRS'] >= 5])
print(f"\nChampions with SRS of 5 or higher: {high_srs_champs} out of {len(champions)}")
print(f"Losers with SRS of 5 or higher: {high_srs_losers} out of {len(losers)}")

print(f"\nLowest SRS champion: {champions.loc[champions['SRS'].idxmin(), 'Year']} "
      f"{champions.loc[champions['SRS'].idxmin(), 'Team']} — SRS: {champions['SRS'].min():.2f}")
print(f"Highest SRS champion: {champions.loc[champions['SRS'].idxmax(), 'Year']} "
      f"{champions.loc[champions['SRS'].idxmax(), 'Team']} — SRS: {champions['SRS'].max():.2f}")

analytics_champs = champions[champions['Era'] == 'A']
analytics_losers = losers[losers['Era'] == 'A']
print(f"\nAnalytics Era 3PA:")
print(f"Champion avg 3PA: {analytics_champs['3PA'].mean():.1f}")
print(f"Loser avg 3PA: {analytics_losers['3PA'].mean():.1f}")

high_nr_champs = len(champions[champions['Net Rating'] >= 5])
high_nr_losers = len(losers[losers['Net Rating'] >= 5])
print(f"\nChampions with Net Rating of 5 or higher: {high_nr_champs} out of {len(champions)}")
print(f"Losers with Net Rating of 5 or higher: {high_nr_losers} out of {len(losers)}")

low_drtg_champs = len(champions[champions['DRtg'] <= 107])
low_drtg_losers = len(losers[losers['DRtg'] <= 107])
print(f"\nChampions with DRtg at or below 107: {low_drtg_champs} out of {len(champions)}")
print(f"Losers with DRtg at or below 107: {low_drtg_losers} out of {len(losers)}")

# ── COACH FACE ANALYSIS ──────────────────────────────────────
coach_data = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-coach-face.csv', encoding='latin1')
coach_data.columns = coach_data.columns.str.strip()

print("\nCOACH FACE SCORES BY RESULT:")
print(coach_data.groupby('Result')['Coach Face Score'].mean())

print("\nCHAMPION COACH FACE SCORES:")
print(coach_data[coach_data['Result'] == 'Champion'][['Year', 'Team', 'Coach', 'Coach Face Score']])

print("\nLOSER COACH FACE SCORES:")
print(coach_data[coach_data['Result'] == 'Loser'][['Year', 'Team', 'Coach', 'Coach Face Score']])

champ_cf = coach_data[coach_data['Result'] == 'Champion']['Coach Face Score'].mean()
loser_cf = coach_data[coach_data['Result'] == 'Loser']['Coach Face Score'].mean()
print(f"\nAverage Champion Coach Face Score: {champ_cf:.2f}")
print(f"Average Loser Coach Face Score: {loser_cf:.2f}")
print(f"Gap: {champ_cf - loser_cf:.2f}")
print(f"NOTE: n=20 (10 champion/loser pairs) - not yet expanded to all 74 teams.")