# -*- coding: utf-8 -*-
"""championship-cube-era-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSwaBZwXUwJupPXmIV_m2fpSayopnHcd
"""

import os
import shutil
# Organize files to match GitHub /Data structure locally in Colab
if not os.path.exists('/content/Data'):
    os.makedirs('/content/Data')
    files_to_move = [
        'championship-cube-master-dataset(Winner).csv',
        'championship-cube-master-dataset(Lossers).csv',
        'championship-cube-coach-face.csv'
    ]
    for f in files_to_move:
        if os.path.exists(f'/content/{f}'):
            shutil.move(f'/content/{f}', f'/content/Data/{f}')
    print('Files organized into /content/Data/')
else:
    print('/content/Data/ directory is ready.')

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# 1. LOAD DATA FROM /Data/
try:
    champions = pd.read_csv('/content/Data/championship-cube-master-dataset(Winner).csv')
    losers = pd.read_csv('/content/Data/championship-cube-master-dataset(Lossers).csv')
    coach_data = pd.read_csv('/content/Data/championship-cube-coach-face.csv', encoding='latin1')

    for df in [champions, losers, coach_data]:
        df.columns = df.columns.str.strip()

    # 2. STANDARDIZE & PREPARE DATA
    coach_data['Coach Face Score'] = pd.to_numeric(coach_data['Coach Face Score'], errors='coerce')
    coach_data['Result'] = coach_data['Result'].replace('Runner-Up', 'Loser')

    champions['Result_Binary'] = 1
    losers['Result_Binary'] = 0
    combined = pd.concat([champions, losers])

    print("Data loaded successfully from /Data/.")

    # 3. LOGISTIC REGRESSION
    features = ['SRS', 'Net Rating', 'DRtg']
    X_raw = combined[features].values
    y = combined['Result_Binary'].values

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_raw)

    model = LogisticRegression()
    model.fit(X_scaled, y)

    print(f"Classification Accuracy: {model.score(X_scaled, y)*100:.1f}%")

except Exception as e:
    print(f"Error: {e}")

import matplotlib.pyplot as plt
import seaborn as sns

try:
    sns.set_theme(style='whitegrid')
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

    # Visualization 1: The SRS Gap
    era_data = combined.groupby(['Era', 'Result_Binary'])['SRS'].mean().reset_index()
    era_data['Result'] = era_data['Result_Binary'].map({1: 'Champion', 0: 'Loser'})
    sns.barplot(x='Era', y='SRS', hue='Result', data=era_data, palette='magma', ax=ax1)
    ax1.set_title('SRS Gap: Champions vs Losers by Era')

    # Visualization 2: Coach Face Scores
    sns.barplot(x='Result', y='Coach Face Score', data=coach_data, palette='viridis', ax=ax2)
    ax2.set_title('Mean Coach Face Score by Result')

    plt.tight_layout()
    plt.show()
except NameError:
    print("Data not loaded. Please run cell zCkEojlpSR3u first.")

from sklearn.model_selection import StratifiedKFold, cross_val_score
import matplotlib.pyplot as plt
import seaborn as sns

# Robust Evaluation using cross-validation
try:
    # Using global variables X_scaled and y defined in zCkEojlpSR3u
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_scores = cross_val_score(LogisticRegression(), X_scaled, y, cv=skf)

    print(f"Robust Cross-Validated Accuracy: {cv_scores.mean():.1%}")

    # Feature Importance Visualization
    plt.figure(figsize=(8, 5))
    sns.barplot(x=['SRS', 'Net Rating', 'DRtg'], y=model.coef_[0], palette='viridis')
    plt.axhline(0, color='black', linewidth=0.8)
    plt.title('Feature Importance (The Cube Dimensions)')
    plt.ylabel('Effect Size')
    plt.show()
except NameError:
    print("Variables X_scaled or y not found. Please run the data loading cell first.")

"""### Final Executive Dashboard: The Championship Cube Differentiation
This visualization serves as the 'money slide' for the contest, showing exactly how Champions separate themselves from the field across all metrics.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Create a summary DataFrame for the 'Cube' dimensions
summary_data = combined.melt(id_vars=['Result_Binary'], value_vars=['SRS', 'Net Rating', 'DRtg'], var_name='Metric', value_name='Value')
summary_data['Result'] = summary_data['Result_Binary'].map({1: 'Champion', 0: 'Loser'})

plt.figure(figsize=(12, 6))
sns.boxplot(x='Metric', y='Value', hue='Result', data=summary_data, palette='Set2')
plt.title('The Championship Cube: Metric Distributions by Result', fontsize=15)
plt.ylabel('Score / Rating')
plt.xlabel('Cube Dimension')
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.show()

"""### Statistical Significance Testing
To ensure this research is contest-ready, we perform a T-test on the Coach Face Score to determine if the 0.32 gap is statistically significant.
"""

from scipy import stats

# Extract scores for both groups, dropping NaNs to ensure a clean test
champ_scores = coach_data[coach_data['Result'] == 'Champion']['Coach Face Score'].dropna()
loser_scores = coach_data[coach_data['Result'] == 'Loser']['Coach Face Score'].dropna()

t_stat, p_val = stats.ttest_ind(champ_scores, loser_scores)

print(f"--- Statistical Significance Report ---")
print(f"T-Statistic: {t_stat:.4f}")
print(f"P-Value: {p_val:.4f}")

if p_val < 0.05:
    print("\nRESULT: Statistically Significant (p < 0.05). The Coach Face Score is a valid differentiator.")
else:
    print("\nRESULT: Not Statistically Significant at the 5% level. Suggests a larger sample size may be needed.")

"""# MIT Sloan 2027: Final Research Summary

### Key Findings:
1. **Predictive Power**: The 'Championship Cube' (SRS, Net Rating, DRtg) remains a strong indicator, predicting winners with **58.1% accuracy**.
2. **Evolution of the Game**: Champions in the Analytics Era attempt **154% more three-pointers** than those in the Physical Era, reflecting a fundamental shift in winning blueprints.
3. **Psychological Metrics**: While Champions possess a higher average **Coach Face Score (1.95 vs 1.62)**, the current sample size (n=74) does not yet reach the 5% statistical significance threshold (p=0.61).

### Recommendation for Future Research:
Expand the 'Coach Face' dataset to include all playoff teams (not just finalists) to reach the required power for statistical significance.
"""

print(champions[champions.duplicated(subset=['Year'], keep=False)])
print(losers[losers.duplicated(subset=['Year'], keep=False)])

champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
print(f"Champions: {len(champions)} rows before any modifications")

print(champions['Year'].value_counts().sort_index())

# Extended Analysis — Sections 2.4 and 2.5

# 3PA and 3P% by era
era_3p = champions.groupby('Era')[['3PA', '3P%']].mean()
print("Champion 3PA and 3P% by Era:")
print(era_3p)

# Pace evolution
print("\nPace Evolution by Era:")
print(f"Physical Era Champions: {champions[champions['Era']=='P']['Pace'].mean():.2f}")
print(f"Transition Era Champions: {champions[champions['Era']=='T']['Pace'].mean():.2f}")
print(f"Analytics Era Champions: {champions[champions['Era']=='A']['Pace'].mean():.2f}")

# Overall champion vs loser across all eras
print("\nOVERALL CHAMPIONS vs LOSERS (all eras combined):")
print(f"Champion avg SRS: {champions['SRS'].mean():.2f}")
print(f"Loser avg SRS: {losers['SRS'].mean():.2f}")
print(f"Champion avg DRtg: {champions['DRtg'].mean():.2f}")
print(f"Loser avg DRtg: {losers['DRtg'].mean():.2f}")
print(f"Champion avg Net Rating: {champions['Net Rating'].mean():.2f}")
print(f"Loser avg Net Rating: {losers['Net Rating'].mean():.2f}")

# SRS threshold analysis
high_srs_champs = len(champions[champions['SRS'] >= 5])
high_srs_losers = len(losers[losers['SRS'] >= 5])
print(f"\nChampions with SRS above 5: {high_srs_champs} out of {len(champions)}")
print(f"Losers with SRS above 5: {high_srs_losers} out of {len(losers)}")

# Lowest and highest SRS champions
print(f"\nLowest SRS champion: {champions.loc[champions['SRS'].idxmin(), 'Year']} {champions.loc[champions['SRS'].idxmin(), 'Team']} — SRS: {champions['SRS'].min():.2f}")
print(f"Highest SRS champion: {champions.loc[champions['SRS'].idxmax(), 'Year']} {champions.loc[champions['SRS'].idxmax(), 'Team']} — SRS: {champions['SRS'].max():.2f}")

# Analytics Era 3PA comparison
analytics_champs = champions[champions['Era'] == 'A']
analytics_losers = losers[losers['Era'] == 'A']
print(f"\nAnalytics Era 3PA:")
print(f"Champion avg 3PA: {analytics_champs['3PA'].mean():.1f}")
print(f"Loser avg 3PA: {analytics_losers['3PA'].mean():.1f}")

# Net Rating threshold
high_nr_champs = len(champions[champions['Net Rating'] >= 5])
high_nr_losers = len(losers[losers['Net Rating'] >= 5])
print(f"\nChampions with Net Rating above 5: {high_nr_champs} out of {len(champions)}")
print(f"Losers with Net Rating above 5: {high_nr_losers} out of {len(losers)}")

# DRtg threshold
low_drtg_champs = len(champions[champions['DRtg'] <= 107])
low_drtg_losers = len(losers[losers['DRtg'] <= 107])
print(f"\nChampions with DRtg at or below 107: {low_drtg_champs} out of {len(champions)}")
print(f"Losers with DRtg at or below 107: {low_drtg_losers} out of {len(losers)}")

import pandas as pd

try:
    # Using the path consistent with the organized folder structure
    coach_data = pd.read_csv('/content/Data/championship-cube-coach-face.csv', encoding='latin1')
    coach_data.columns = coach_data.columns.str.strip()

    # Standardize data types and result values
    coach_data['Coach Face Score'] = pd.to_numeric(coach_data['Coach Face Score'], errors='coerce')
    coach_data['Result'] = coach_data['Result'].replace('Runner-Up', 'Loser')

    champ_avg = coach_data[coach_data['Result']=='Champion']['Coach Face Score'].mean()
    loser_avg = coach_data[coach_data['Result']=='Loser']['Coach Face Score'].mean()
    n_total = len(coach_data.dropna(subset=['Coach Face Score']))

    print(f"Average Champion Coach Face Score: {champ_avg:.2f}")
    print(f"Average Loser Coach Face Score: {loser_avg:.2f}")
    print(f"Gap: {champ_avg - loser_avg:.2f}")
    print(f"Sample size: n={n_total}")
except Exception as e:
    print(f"Error: {e}")

# ── COACH FACE ANALYSIS ──────────────────────────────────────
try:
    # Updated path to match the organized /Data folder structure
    coach_data = pd.read_csv('/content/Data/championship-cube-coach-face.csv', encoding='latin1')
    coach_data.columns = coach_data.columns.str.strip()

    # Convert 'Coach Face Score' to numeric, coercing errors to NaN
    coach_data['Coach Face Score'] = pd.to_numeric(coach_data['Coach Face Score'], errors='coerce')

    # Standardize 'Result' column: replace 'Runner-Up' with 'Loser'
    coach_data['Result'] = coach_data['Result'].replace('Runner-Up', 'Loser')

    print("\nCOACH FACE SCORES BY RESULT:")
    print(coach_data.groupby('Result')['Coach Face Score'].mean())

    print("\nCHAMPION COACH FACE SCORES:")
    print(coach_data[coach_data['Result'] == 'Champion'][['Year', 'Team', 'Coach', 'Coach Face Score']])

    print("\nLOSER COACH FACE SCORES:")
    print(coach_data[coach_data['Result'] == 'Loser'][['Year', 'Team', 'Coach', 'Coach Face Score']])

    champ_cf = coach_data[coach_data['Result'] == 'Champion']['Coach Face Score'].mean()
    loser_cf = coach_data[coach_data['Result'] == 'Loser']['Coach Face Score'].mean()
    n_total = len(coach_data.dropna(subset=['Coach Face Score']))

    print(f"\nAverage Champion Coach Face Score: {champ_cf:.2f}")
    print(f"Average Loser Coach Face Score: {loser_cf:.2f}")
    print(f"Gap: {champ_cf - loser_cf:.2f}")
    print(f"NOTE: n={n_total} teams analyzed from the updated dataset.")
except FileNotFoundError:
    print("Error: The file was not found in /content/Data/. Please ensure cell 983e0c37 was executed successfully.")