# -*- coding: utf-8 -*-
"""championship-cube-era-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSwaBZwXUwJupPXmIV_m2fpSayopnHcd
"""

# Championship Cube — Complete Analysis Script
# Supporting research for MIT Sloan Sports Analytics Conference 2027
# Data sourced from Basketball Reference

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# ── 1. LOAD DATA ──────────────────────────────────────────────
champions = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-champions.csv')

losers = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-losers.csv')

# Clean column names
champions.columns = champions.columns.str.strip()
losers.columns = losers.columns.str.strip()

print("Data loaded successfully")
print(f"Champions: {len(champions)} rows")
print(f"Losers: {len(losers)} rows")

# ── 2. ERA ANALYSIS ───────────────────────────────────────────
era_champs = champions.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()
era_losers = losers.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()

print("\nCHAMPIONS BY ERA:")
print(era_champs)
print("\nFINALS LOSERS BY ERA:")
print(era_losers)

# ── 3. GAP ANALYSIS ───────────────────────────────────────────
print("\nSRS GAP BY ERA (Champions minus Losers):")
print(era_champs['SRS'] - era_losers['SRS'])

print("\nNet Rating GAP BY ERA:")
print(era_champs['Net Rating'] - era_losers['Net Rating'])

print("\nDRtg GAP BY ERA:")
print(era_champs['DRtg'] - era_losers['DRtg'])

# ── 4. LOGISTIC REGRESSION ────────────────────────────────────
champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
combined = pd.concat([champions, losers])
combined.columns = combined.columns.str.strip()

X = combined[['SRS', 'Net Rating', 'DRtg']].values
y = combined['Result_Binary'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression()
model.fit(X_scaled, y)

print("\nLOGISTIC REGRESSION RESULTS:")
print(f"SRS Coefficient: {model.coef_[0][0]:.3f}")
print(f"Net Rating Coefficient: {model.coef_[0][1]:.3f}")
print(f"DRtg Coefficient: {model.coef_[0][2]:.3f}")
print(f"Classification Accuracy: {model.score(X_scaled, y):.1%}")

print(champions[champions.duplicated(subset=['Year'], keep=False)])
print(losers[losers.duplicated(subset=['Year'], keep=False)])

champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
print(f"Champions: {len(champions)} rows before any modifications")

print(champions['Year'].value_counts().sort_index())