# -*- coding: utf-8 -*-
"""championship-cube-era-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gSwaBZwXUwJupPXmIV_m2fpSayopnHcd
"""

# Championship Cube — Complete Analysis Script
# Supporting research for MIT Sloan Sports Analytics Conference 2027
# Data sourced from Basketball Reference

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

# ── 1. LOAD DATA ──────────────────────────────────────────────
champions = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-champions.csv')

losers = pd.read_csv('https://raw.githubusercontent.com/ChampionshipCube-Sloan2027/The-Championship-Cube-A-Front-Office-Framework-for-Building-NBA-Champions/main/championship-cube-losers.csv')

# Clean column names
champions.columns = champions.columns.str.strip()
losers.columns = losers.columns.str.strip()

print("Data loaded successfully")
print(f"Champions: {len(champions)} rows")
print(f"Losers: {len(losers)} rows")

# ── 2. ERA ANALYSIS ───────────────────────────────────────────
era_champs = champions.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()
era_losers = losers.groupby('Era')[['SRS', 'DRtg', 'Net Rating', 'Pace']].mean()

print("\nCHAMPIONS BY ERA:")
print(era_champs)
print("\nFINALS LOSERS BY ERA:")
print(era_losers)

# ── 3. GAP ANALYSIS ───────────────────────────────────────────
print("\nSRS GAP BY ERA (Champions minus Losers):")
print(era_champs['SRS'] - era_losers['SRS'])

print("\nNet Rating GAP BY ERA:")
print(era_champs['Net Rating'] - era_losers['Net Rating'])

print("\nDRtg GAP BY ERA:")
print(era_champs['DRtg'] - era_losers['DRtg'])

# ── 4. LOGISTIC REGRESSION ────────────────────────────────────
champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
combined = pd.concat([champions, losers])
combined.columns = combined.columns.str.strip()

X = combined[['SRS', 'Net Rating', 'DRtg']].values
y = combined['Result_Binary'].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

model = LogisticRegression()
model.fit(X_scaled, y)

print("\nLOGISTIC REGRESSION RESULTS:")
print(f"SRS Coefficient: {model.coef_[0][0]:.3f}")
print(f"Net Rating Coefficient: {model.coef_[0][1]:.3f}")
print(f"DRtg Coefficient: {model.coef_[0][2]:.3f}")
print(f"Classification Accuracy: {model.score(X_scaled, y):.1%}")

print(champions[champions.duplicated(subset=['Year'], keep=False)])
print(losers[losers.duplicated(subset=['Year'], keep=False)])

champions['Result_Binary'] = 1
losers['Result_Binary'] = 0
print(f"Champions: {len(champions)} rows before any modifications")

print(champions['Year'].value_counts().sort_index())

# Extended Analysis — Sections 2.4 and 2.5

# 3PA and 3P% by era
era_3p = champions.groupby('Era')[['3PA', '3P%']].mean()
print("Champion 3PA and 3P% by Era:")
print(era_3p)

# Pace evolution
print("\nPace Evolution by Era:")
print(f"Physical Era Champions: {champions[champions['Era']=='P']['Pace'].mean():.2f}")
print(f"Transition Era Champions: {champions[champions['Era']=='T']['Pace'].mean():.2f}")
print(f"Analytics Era Champions: {champions[champions['Era']=='A']['Pace'].mean():.2f}")

# Overall champion vs loser across all eras
print("\nOVERALL CHAMPIONS vs LOSERS (all eras combined):")
print(f"Champion avg SRS: {champions['SRS'].mean():.2f}")
print(f"Loser avg SRS: {losers['SRS'].mean():.2f}")
print(f"Champion avg DRtg: {champions['DRtg'].mean():.2f}")
print(f"Loser avg DRtg: {losers['DRtg'].mean():.2f}")
print(f"Champion avg Net Rating: {champions['Net Rating'].mean():.2f}")
print(f"Loser avg Net Rating: {losers['Net Rating'].mean():.2f}")

# SRS threshold analysis
high_srs_champs = len(champions[champions['SRS'] >= 5])
high_srs_losers = len(losers[losers['SRS'] >= 5])
print(f"\nChampions with SRS above 5: {high_srs_champs} out of {len(champions)}")
print(f"Losers with SRS above 5: {high_srs_losers} out of {len(losers)}")

# Lowest and highest SRS champions
print(f"\nLowest SRS champion: {champions.loc[champions['SRS'].idxmin(), 'Year']} {champions.loc[champions['SRS'].idxmin(), 'Team']} — SRS: {champions['SRS'].min():.2f}")
print(f"Highest SRS champion: {champions.loc[champions['SRS'].idxmax(), 'Year']} {champions.loc[champions['SRS'].idxmax(), 'Team']} — SRS: {champions['SRS'].max():.2f}")

# Analytics Era 3PA comparison
analytics_champs = champions[champions['Era'] == 'A']
analytics_losers = losers[losers['Era'] == 'A']
print(f"\nAnalytics Era 3PA:")
print(f"Champion avg 3PA: {analytics_champs['3PA'].mean():.1f}")
print(f"Loser avg 3PA: {analytics_losers['3PA'].mean():.1f}")

# Net Rating threshold
high_nr_champs = len(champions[champions['Net Rating'] >= 5])
high_nr_losers = len(losers[losers['Net Rating'] >= 5])
print(f"\nChampions with Net Rating above 5: {high_nr_champs} out of {len(champions)}")
print(f"Losers with Net Rating above 5: {high_nr_losers} out of {len(losers)}")

# DRtg threshold
low_drtg_champs = len(champions[champions['DRtg'] <= 107])
low_drtg_losers = len(losers[losers['DRtg'] <= 107])
print(f"\nChampions with DRtg at or below 107: {low_drtg_champs} out of {len(champions)}")
print(f"Losers with DRtg at or below 107: {low_drtg_losers} out of {len(losers)}")